### ISSUE TITLE
getName

### ISSUE THREAD

**Issue by ancjf** [ensdomains/ensjs-v3#91]
I will run the code below:

async function test(){
    let ens = new ENS();
    try{
        let name = await ens.getName('0xF11804c522753E2afd2a4a8d9c1BF7AB0ABAf60f')
        console.log(name)
    }catch (e){
        console.log(e)
    }
}

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/mnt/c/src/test/js/ens/node_modules/@ensdomains/ensjs/dist/cjs/functions/initialGetters' imported from /mnt/c/src/test/js/ens/node_modules/@ensdomains/ensjs/dist/cjs/index.js
    at new NodeError (internal/errors.js:322:7)
    at finalizeResolution (internal/modules/esm/resolve.js:308:11)
    at moduleResolve (internal/modules/esm/resolve.js:731:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:842:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at Loader.import (internal/modules/esm/loader.js:177:28)
    at importModuleDynamically (internal/modules/cjs/loader.js:1028:27)
    at exports.importModuleDynamicallyCallback (internal/process/esm_loader.js:30:14)
    at ENS.mainFunc [as getName] (/mnt/c/src/test/js/ens/node_modules/@ensdomains/ensjs/dist/cjs/index.js:64:26) {
  code: 'ERR_MODULE_NOT_FOUND'
}

"@ensdomains/ensjs@^3.0.0-alpha.39":
  version "3.0.0-alpha.39"
node: v14.18.0

why?

**Comment by Magofoco** [comment]
Can you show how:
- you imported the ens library
- how did you connect to it
- which provider did you use
?

This works for me
```js
import { ENS } from "@ensdomains/ensjs";
const INFURA_NODE_MAINNET = `https://mainnet.infura.io/v3/${INFURA_API_KEY}`;
const provider = new ethers.providers.JsonRpcProvider(INFURA_NODE_GOERLI);
const ENSInstance = new ENS();

const main = async ( ) => {
    
    const pollingFunction = async () => { 
        await ENSInstance.setProvider(provider);
        const name = await ENSInstance.getName(
          "0xF11804c522753E2afd2a4a8d9c1BF7AB0ABAf60f"
        );
        console.log(name);
    }
    
  setInterval(pollingFunction, 20000);

}
main()
```
